---
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Install gpg
      run: brew install gnupg
    
    - name: Setup provisioning profile
      env:
        IOS_KEYS: ${{ secrets.IOS_KEYS }}
      run: ./.github/secrets/decrypt_secrets.sh
    
    - name: Archiving project
      env:
        PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
      run: ./.github/scripts/archive_app.sh
    
    - name: Exporting .ipa
      run: ./.github/scripts/export_ipa.sh


